<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('districts', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->unsignedInteger('lg_code')->nullable();
            $table->foreignId('state_id')->constrained('states');
            $table->boolean('is_active')->default(true);
            $table->softDeletes();
        });
        DB::table('districts')->insert([
            ['id'=>'1','lg_code'=>'603','name'=>'Nicobars','state_id'=>'1'],
            ['id'=>'2','lg_code'=>'632','name'=>'North And Middle Andaman','state_id'=>'1'],
            ['id'=>'3','lg_code'=>'602','name'=>'South Andamans','state_id'=>'1'],
            ['id'=>'4','lg_code'=>'745','name'=>'Alluri Sitharama Raju','state_id'=>'2'],
            ['id'=>'5','lg_code'=>'744','name'=>'Anakapalli','state_id'=>'2'],
            ['id'=>'6','lg_code'=>'502','name'=>'Ananthapuramu','state_id'=>'2'],
            ['id'=>'7','lg_code'=>'753','name'=>'Annamayya','state_id'=>'2'],
            ['id'=>'8','lg_code'=>'750','name'=>'Bapatla','state_id'=>'2'],
            ['id'=>'9','lg_code'=>'503','name'=>'Chittoor','state_id'=>'2'],
            ['id'=>'10','lg_code'=>'747','name'=>'Dr. B.R. Ambedkar Konaseema','state_id'=>'2'],
            ['id'=>'11','lg_code'=>'505','name'=>'East Godavari','state_id'=>'2'],
            ['id'=>'12','lg_code'=>'748','name'=>'Eluru','state_id'=>'2'],
            ['id'=>'13','lg_code'=>'506','name'=>'Guntur','state_id'=>'2'],
            ['id'=>'14','lg_code'=>'746','name'=>'Kakinada','state_id'=>'2'],
            ['id'=>'15','lg_code'=>'510','name'=>'Krishna','state_id'=>'2'],
            ['id'=>'16','lg_code'=>'511','name'=>'Kurnool','state_id'=>'2'],
            ['id'=>'17','lg_code'=>'755','name'=>'Nandyal','state_id'=>'2'],
            ['id'=>'18','lg_code'=>'749','name'=>'Ntr','state_id'=>'2'],
            ['id'=>'19','lg_code'=>'751','name'=>'Palnadu','state_id'=>'2'],
            ['id'=>'20','lg_code'=>'743','name'=>'Parvathipuram Manyam','state_id'=>'2'],
            ['id'=>'21','lg_code'=>'517','name'=>'Prakasam','state_id'=>'2'],
            ['id'=>'22','lg_code'=>'519','name'=>'Srikakulam','state_id'=>'2'],
            ['id'=>'23','lg_code'=>'515','name'=>'Sri Potti Sriramulu Nellore','state_id'=>'2'],
            ['id'=>'24','lg_code'=>'754','name'=>'Sri Sathya Sai','state_id'=>'2'],
            ['id'=>'25','lg_code'=>'752','name'=>'Tirupati','state_id'=>'2'],
            ['id'=>'26','lg_code'=>'520','name'=>'Visakhapatnam','state_id'=>'2'],
            ['id'=>'27','lg_code'=>'521','name'=>'Vizianagaram','state_id'=>'2'],
            ['id'=>'28','lg_code'=>'523','name'=>'West Godavari','state_id'=>'2'],
            ['id'=>'29','lg_code'=>'504','name'=>'Y.S.R.','state_id'=>'2'],
            ['id'=>'30','lg_code'=>'628','name'=>'Anjaw','state_id'=>'3'],
            ['id'=>'31','lg_code'=>'787','name'=>'Bichom','state_id'=>'3'],
            ['id'=>'32','lg_code'=>'229','name'=>'Changlang','state_id'=>'3'],
            ['id'=>'33','lg_code'=>'230','name'=>'Dibang Valley','state_id'=>'3'],
            ['id'=>'34','lg_code'=>'231','name'=>'East Kameng','state_id'=>'3'],
            ['id'=>'35','lg_code'=>'232','name'=>'East Siang','state_id'=>'3'],
            ['id'=>'36','lg_code'=>'718','name'=>'Kamle','state_id'=>'3'],
            ['id'=>'37','lg_code'=>'786','name'=>'Keyi Panyor','state_id'=>'3'],
            ['id'=>'38','lg_code'=>'677','name'=>'Kra Daadi','state_id'=>'3'],
            ['id'=>'39','lg_code'=>'233','name'=>'Kurung Kumey','state_id'=>'3'],
            ['id'=>'40','lg_code'=>'724','name'=>'Leparada','state_id'=>'3'],
            ['id'=>'41','lg_code'=>'234','name'=>'Lohit','state_id'=>'3'],
            ['id'=>'42','lg_code'=>'666','name'=>'Longding','state_id'=>'3'],
            ['id'=>'43','lg_code'=>'235','name'=>'Lower Dibang Valley','state_id'=>'3'],
            ['id'=>'44','lg_code'=>'719','name'=>'Lower Siang','state_id'=>'3'],
            ['id'=>'45','lg_code'=>'236','name'=>'Lower Subansiri','state_id'=>'3'],
            ['id'=>'46','lg_code'=>'678','name'=>'Namsai','state_id'=>'3'],
            ['id'=>'47','lg_code'=>'723','name'=>'Pakke Kessang','state_id'=>'3'],
            ['id'=>'48','lg_code'=>'237','name'=>'Papum Pare','state_id'=>'3'],
            ['id'=>'49','lg_code'=>'725','name'=>'Shi Yomi','state_id'=>'3'],
            ['id'=>'50','lg_code'=>'679','name'=>'Siang','state_id'=>'3'],
            ['id'=>'51','lg_code'=>'238','name'=>'Tawang','state_id'=>'3'],
            ['id'=>'52','lg_code'=>'239','name'=>'Tirap','state_id'=>'3'],
            ['id'=>'53','lg_code'=>'240','name'=>'Upper Siang','state_id'=>'3'],
            ['id'=>'54','lg_code'=>'241','name'=>'Upper Subansiri','state_id'=>'3'],
            ['id'=>'55','lg_code'=>'242','name'=>'West Kameng','state_id'=>'3'],
            ['id'=>'56','lg_code'=>'243','name'=>'West Siang','state_id'=>'3'],
            ['id'=>'57','lg_code'=>'739','name'=>'Bajali','state_id'=>'4'],
            ['id'=>'58','lg_code'=>'616','name'=>'Baksa','state_id'=>'4'],
            ['id'=>'59','lg_code'=>'280','name'=>'Barpeta','state_id'=>'4'],
            ['id'=>'60','lg_code'=>'705','name'=>'Biswanath','state_id'=>'4'],
            ['id'=>'61','lg_code'=>'281','name'=>'Bongaigaon','state_id'=>'4'],
            ['id'=>'62','lg_code'=>'282','name'=>'Cachar','state_id'=>'4'],
            ['id'=>'63','lg_code'=>'708','name'=>'Charaideo','state_id'=>'4'],
            ['id'=>'64','lg_code'=>'612','name'=>'Chirang','state_id'=>'4'],
            ['id'=>'65','lg_code'=>'283','name'=>'Darrang','state_id'=>'4'],
            ['id'=>'66','lg_code'=>'284','name'=>'Dhemaji','state_id'=>'4'],
            ['id'=>'67','lg_code'=>'285','name'=>'Dhubri','state_id'=>'4'],
            ['id'=>'68','lg_code'=>'286','name'=>'Dibrugarh','state_id'=>'4'],
            ['id'=>'69','lg_code'=>'299','name'=>'Dima Hasao','state_id'=>'4'],
            ['id'=>'70','lg_code'=>'287','name'=>'Goalpara','state_id'=>'4'],
            ['id'=>'71','lg_code'=>'288','name'=>'Golaghat','state_id'=>'4'],
            ['id'=>'72','lg_code'=>'289','name'=>'Hailakandi','state_id'=>'4'],
            ['id'=>'73','lg_code'=>'709','name'=>'Hojai','state_id'=>'4'],
            ['id'=>'74','lg_code'=>'290','name'=>'Jorhat','state_id'=>'4'],
            ['id'=>'75','lg_code'=>'291','name'=>'Kamrup','state_id'=>'4'],
            ['id'=>'76','lg_code'=>'618','name'=>'Kamrup Metro','state_id'=>'4'],
            ['id'=>'77','lg_code'=>'292','name'=>'Karbi Anglong','state_id'=>'4'],
            ['id'=>'78','lg_code'=>'293','name'=>'Sri Bhumi','state_id'=>'4'],
            ['id'=>'79','lg_code'=>'294','name'=>'Kokrajhar','state_id'=>'4'],
            ['id'=>'80','lg_code'=>'295','name'=>'Lakhimpur','state_id'=>'4'],
            ['id'=>'81','lg_code'=>'706','name'=>'Majuli','state_id'=>'4'],
            ['id'=>'82','lg_code'=>'296','name'=>'Marigaon','state_id'=>'4'],
            ['id'=>'83','lg_code'=>'297','name'=>'Nagaon','state_id'=>'4'],
            ['id'=>'84','lg_code'=>'298','name'=>'Nalbari','state_id'=>'4'],
            ['id'=>'85','lg_code'=>'300','name'=>'Sivasagar','state_id'=>'4'],
            ['id'=>'86','lg_code'=>'301','name'=>'Sonitpur','state_id'=>'4'],
            ['id'=>'87','lg_code'=>'707','name'=>'South Salmara Mancachar','state_id'=>'4'],
            ['id'=>'88','lg_code'=>'756','name'=>'Tamulpur','state_id'=>'4'],
            ['id'=>'89','lg_code'=>'302','name'=>'Tinsukia','state_id'=>'4'],
            ['id'=>'90','lg_code'=>'617','name'=>'Udalguri','state_id'=>'4'],
            ['id'=>'91','lg_code'=>'710','name'=>'West Karbi Anglong','state_id'=>'4'],
            ['id'=>'92','lg_code'=>'188','name'=>'Araria','state_id'=>'5'],
            ['id'=>'93','lg_code'=>'611','name'=>'Arwal','state_id'=>'5'],
            ['id'=>'94','lg_code'=>'189','name'=>'Aurangabad','state_id'=>'5'],
            ['id'=>'95','lg_code'=>'190','name'=>'Banka','state_id'=>'5'],
            ['id'=>'96','lg_code'=>'191','name'=>'Begusarai','state_id'=>'5'],
            ['id'=>'97','lg_code'=>'192','name'=>'Bhagalpur','state_id'=>'5'],
            ['id'=>'98','lg_code'=>'193','name'=>'Bhojpur','state_id'=>'5'],
            ['id'=>'99','lg_code'=>'194','name'=>'Buxar','state_id'=>'5'],
            ['id'=>'100','lg_code'=>'195','name'=>'Darbhanga','state_id'=>'5'],
            ['id'=>'101','lg_code'=>'196','name'=>'Gaya','state_id'=>'5'],
            ['id'=>'102','lg_code'=>'197','name'=>'Gopalganj','state_id'=>'5'],
            ['id'=>'103','lg_code'=>'198','name'=>'Jamui','state_id'=>'5'],
            ['id'=>'104','lg_code'=>'199','name'=>'Jehanabad','state_id'=>'5'],
            ['id'=>'105','lg_code'=>'200','name'=>'Kaimur (Bhabua)','state_id'=>'5'],
            ['id'=>'106','lg_code'=>'201','name'=>'Katihar','state_id'=>'5'],
            ['id'=>'107','lg_code'=>'202','name'=>'Khagaria','state_id'=>'5'],
            ['id'=>'108','lg_code'=>'203','name'=>'Kishanganj','state_id'=>'5'],
            ['id'=>'109','lg_code'=>'204','name'=>'Lakhisarai','state_id'=>'5'],
            ['id'=>'110','lg_code'=>'205','name'=>'Madhepura','state_id'=>'5'],
            ['id'=>'111','lg_code'=>'206','name'=>'Madhubani','state_id'=>'5'],
            ['id'=>'112','lg_code'=>'207','name'=>'Munger','state_id'=>'5'],
            ['id'=>'113','lg_code'=>'208','name'=>'Muzaffarpur','state_id'=>'5'],
            ['id'=>'114','lg_code'=>'209','name'=>'Nalanda','state_id'=>'5'],
            ['id'=>'115','lg_code'=>'210','name'=>'Nawada','state_id'=>'5'],
            ['id'=>'116','lg_code'=>'211','name'=>'Pashchim Champaran','state_id'=>'5'],
            ['id'=>'117','lg_code'=>'212','name'=>'Patna','state_id'=>'5'],
            ['id'=>'118','lg_code'=>'213','name'=>'Purbi Champaran','state_id'=>'5'],
            ['id'=>'119','lg_code'=>'214','name'=>'Purnia','state_id'=>'5'],
            ['id'=>'120','lg_code'=>'215','name'=>'Rohtas','state_id'=>'5'],
            ['id'=>'121','lg_code'=>'216','name'=>'Saharsa','state_id'=>'5'],
            ['id'=>'122','lg_code'=>'217','name'=>'Samastipur','state_id'=>'5'],
            ['id'=>'123','lg_code'=>'218','name'=>'Saran','state_id'=>'5'],
            ['id'=>'124','lg_code'=>'219','name'=>'Sheikhpura','state_id'=>'5'],
            ['id'=>'125','lg_code'=>'220','name'=>'Sheohar','state_id'=>'5'],
            ['id'=>'126','lg_code'=>'221','name'=>'Sitamarhi','state_id'=>'5'],
            ['id'=>'127','lg_code'=>'222','name'=>'Siwan','state_id'=>'5'],
            ['id'=>'128','lg_code'=>'223','name'=>'Supaul','state_id'=>'5'],
            ['id'=>'129','lg_code'=>'224','name'=>'Vaishali','state_id'=>'5'],
            ['id'=>'130','lg_code'=>'44','name'=>'Chandigarh','state_id'=>'6'],
            ['id'=>'131','lg_code'=>'646','name'=>'Balod','state_id'=>'7'],
            ['id'=>'132','lg_code'=>'644','name'=>'Balodabazar-Bhatapara','state_id'=>'7'],
            ['id'=>'133','lg_code'=>'649','name'=>'Balrampur-Ramanujganj','state_id'=>'7'],
            ['id'=>'134','lg_code'=>'374','name'=>'Bastar','state_id'=>'7'],
            ['id'=>'135','lg_code'=>'650','name'=>'Bemetara','state_id'=>'7'],
            ['id'=>'136','lg_code'=>'636','name'=>'Bijapur','state_id'=>'7'],
            ['id'=>'137','lg_code'=>'375','name'=>'Bilaspur','state_id'=>'7'],
            ['id'=>'138','lg_code'=>'376','name'=>'Dakshin Bastar Dantewada','state_id'=>'7'],
            ['id'=>'139','lg_code'=>'377','name'=>'Dhamtari','state_id'=>'7'],
            ['id'=>'140','lg_code'=>'378','name'=>'Durg','state_id'=>'7'],
            ['id'=>'141','lg_code'=>'645','name'=>'Gariyaband','state_id'=>'7'],
            ['id'=>'142','lg_code'=>'734','name'=>'Gaurela-Pendra-Marwahi','state_id'=>'7'],
            ['id'=>'143','lg_code'=>'379','name'=>'Janjgir-Champa','state_id'=>'7'],
            ['id'=>'144','lg_code'=>'380','name'=>'Jashpur','state_id'=>'7'],
            ['id'=>'145','lg_code'=>'382','name'=>'Kabeerdham','state_id'=>'7'],
            ['id'=>'146','lg_code'=>'759','name'=>'Khairagarh-Chhuikhadan-Gandai','state_id'=>'7'],
            ['id'=>'147','lg_code'=>'643','name'=>'Kondagaon','state_id'=>'7'],
            ['id'=>'148','lg_code'=>'383','name'=>'Korba','state_id'=>'7'],
            ['id'=>'149','lg_code'=>'384','name'=>'Korea','state_id'=>'7'],
            ['id'=>'150','lg_code'=>'385','name'=>'Mahasamund','state_id'=>'7'],
            ['id'=>'151','lg_code'=>'760','name'=>'Manendragarh-Chirmiri-Bharatpur(M C B)','state_id'=>'7'],
            ['id'=>'152','lg_code'=>'761','name'=>'Mohla-Manpur-Ambagarh Chouki','state_id'=>'7'],
            ['id'=>'153','lg_code'=>'647','name'=>'Mungeli','state_id'=>'7'],
            ['id'=>'154','lg_code'=>'637','name'=>'Narayanpur','state_id'=>'7'],
            ['id'=>'155','lg_code'=>'386','name'=>'Raigarh','state_id'=>'7'],
            ['id'=>'156','lg_code'=>'387','name'=>'Raipur','state_id'=>'7'],
            ['id'=>'157','lg_code'=>'388','name'=>'Rajnandgaon','state_id'=>'7'],
            ['id'=>'158','lg_code'=>'762','name'=>'Sakti','state_id'=>'7'],
            ['id'=>'159','lg_code'=>'763','name'=>'Sarangarh-Bilaigarh','state_id'=>'7'],
            ['id'=>'160','lg_code'=>'642','name'=>'Sukma','state_id'=>'7'],
            ['id'=>'161','lg_code'=>'648','name'=>'Surajpur','state_id'=>'7'],
            ['id'=>'162','lg_code'=>'389','name'=>'Surguja','state_id'=>'7'],
            ['id'=>'163','lg_code'=>'381','name'=>'Uttar Bastar Kanker','state_id'=>'7'],
            ['id'=>'164','lg_code'=>'77','name'=>'Central','state_id'=>'8'],
            ['id'=>'165','lg_code'=>'78','name'=>'East','state_id'=>'8'],
            ['id'=>'166','lg_code'=>'79','name'=>'New Delhi','state_id'=>'8'],
            ['id'=>'167','lg_code'=>'80','name'=>'North','state_id'=>'8'],
            ['id'=>'168','lg_code'=>'81','name'=>'North East','state_id'=>'8'],
            ['id'=>'169','lg_code'=>'82','name'=>'North West','state_id'=>'8'],
            ['id'=>'170','lg_code'=>'671','name'=>'Shahdara','state_id'=>'8'],
            ['id'=>'171','lg_code'=>'83','name'=>'South','state_id'=>'8'],
            ['id'=>'172','lg_code'=>'670','name'=>'South East','state_id'=>'8'],
            ['id'=>'173','lg_code'=>'84','name'=>'South West','state_id'=>'8'],
            ['id'=>'174','lg_code'=>'85','name'=>'West','state_id'=>'8'],
            ['id'=>'175','lg_code'=>'551','name'=>'North Goa','state_id'=>'9'],
            ['id'=>'176','lg_code'=>'552','name'=>'South Goa','state_id'=>'9'],
            ['id'=>'177','lg_code'=>'438','name'=>'Ahmedabad','state_id'=>'10'],
            ['id'=>'178','lg_code'=>'439','name'=>'Amreli','state_id'=>'10'],
            ['id'=>'179','lg_code'=>'440','name'=>'Anand','state_id'=>'10'],
            ['id'=>'180','lg_code'=>'672','name'=>'Arvalli','state_id'=>'10'],
            ['id'=>'181','lg_code'=>'441','name'=>'Banas Kantha','state_id'=>'10'],
            ['id'=>'182','lg_code'=>'442','name'=>'Bharuch','state_id'=>'10'],
            ['id'=>'183','lg_code'=>'443','name'=>'Bhavnagar','state_id'=>'10'],
            ['id'=>'184','lg_code'=>'676','name'=>'Botad','state_id'=>'10'],
            ['id'=>'185','lg_code'=>'668','name'=>'Chhotaudepur','state_id'=>'10'],
            ['id'=>'186','lg_code'=>'445','name'=>'Dahod','state_id'=>'10'],
            ['id'=>'187','lg_code'=>'444','name'=>'Dangs','state_id'=>'10'],
            ['id'=>'188','lg_code'=>'674','name'=>'Devbhumi Dwarka','state_id'=>'10'],
            ['id'=>'189','lg_code'=>'446','name'=>'Gandhinagar','state_id'=>'10'],
            ['id'=>'190','lg_code'=>'675','name'=>'Gir Somnath','state_id'=>'10'],
            ['id'=>'191','lg_code'=>'447','name'=>'Jamnagar','state_id'=>'10'],
            ['id'=>'192','lg_code'=>'448','name'=>'Junagadh','state_id'=>'10'],
            ['id'=>'193','lg_code'=>'449','name'=>'Kachchh','state_id'=>'10'],
            ['id'=>'194','lg_code'=>'450','name'=>'Kheda','state_id'=>'10'],
            ['id'=>'195','lg_code'=>'451','name'=>'Mahesana','state_id'=>'10'],
            ['id'=>'196','lg_code'=>'669','name'=>'Mahisagar','state_id'=>'10'],
            ['id'=>'197','lg_code'=>'673','name'=>'Morbi','state_id'=>'10'],
            ['id'=>'198','lg_code'=>'452','name'=>'Narmada','state_id'=>'10'],
            ['id'=>'199','lg_code'=>'453','name'=>'Navsari','state_id'=>'10'],
            ['id'=>'200','lg_code'=>'454','name'=>'Panch Mahals','state_id'=>'10'],
            ['id'=>'201','lg_code'=>'455','name'=>'Patan','state_id'=>'10'],
            ['id'=>'202','lg_code'=>'456','name'=>'Porbandar','state_id'=>'10'],
            ['id'=>'203','lg_code'=>'457','name'=>'Rajkot','state_id'=>'10'],
            ['id'=>'204','lg_code'=>'458','name'=>'Sabar Kantha','state_id'=>'10'],
            ['id'=>'205','lg_code'=>'459','name'=>'Surat','state_id'=>'10'],
            ['id'=>'206','lg_code'=>'460','name'=>'Surendranagar','state_id'=>'10'],
            ['id'=>'207','lg_code'=>'641','name'=>'Tapi','state_id'=>'10'],
            ['id'=>'208','lg_code'=>'461','name'=>'Vadodara','state_id'=>'10'],
            ['id'=>'209','lg_code'=>'462','name'=>'Valsad','state_id'=>'10'],
            ['id'=>'210','lg_code'=>'58','name'=>'Ambala','state_id'=>'11'],
            ['id'=>'211','lg_code'=>'59','name'=>'Bhiwani','state_id'=>'11'],
            ['id'=>'212','lg_code'=>'701','name'=>'Charkhi Dadri','state_id'=>'11'],
            ['id'=>'213','lg_code'=>'60','name'=>'Faridabad','state_id'=>'11'],
            ['id'=>'214','lg_code'=>'61','name'=>'Fatehabad','state_id'=>'11'],
            ['id'=>'215','lg_code'=>'62','name'=>'Gurugram','state_id'=>'11'],
            ['id'=>'216','lg_code'=>'63','name'=>'Hisar','state_id'=>'11'],
            ['id'=>'217','lg_code'=>'64','name'=>'Jhajjar','state_id'=>'11'],
            ['id'=>'218','lg_code'=>'65','name'=>'Jind','state_id'=>'11'],
            ['id'=>'219','lg_code'=>'66','name'=>'Kaithal','state_id'=>'11'],
            ['id'=>'220','lg_code'=>'67','name'=>'Karnal','state_id'=>'11'],
            ['id'=>'221','lg_code'=>'68','name'=>'Kurukshetra','state_id'=>'11'],
            ['id'=>'222','lg_code'=>'69','name'=>'Mahendragarh','state_id'=>'11'],
            ['id'=>'223','lg_code'=>'604','name'=>'Nuh','state_id'=>'11'],
            ['id'=>'224','lg_code'=>'619','name'=>'Palwal','state_id'=>'11'],
            ['id'=>'225','lg_code'=>'70','name'=>'Panchkula','state_id'=>'11'],
            ['id'=>'226','lg_code'=>'71','name'=>'Panipat','state_id'=>'11'],
            ['id'=>'227','lg_code'=>'72','name'=>'Rewari','state_id'=>'11'],
            ['id'=>'228','lg_code'=>'73','name'=>'Rohtak','state_id'=>'11'],
            ['id'=>'229','lg_code'=>'74','name'=>'Sirsa','state_id'=>'11'],
            ['id'=>'230','lg_code'=>'75','name'=>'Sonipat','state_id'=>'11'],
            ['id'=>'231','lg_code'=>'76','name'=>'Yamunanagar','state_id'=>'11'],
            ['id'=>'232','lg_code'=>'15','name'=>'Bilaspur','state_id'=>'12'],
            ['id'=>'233','lg_code'=>'16','name'=>'Chamba','state_id'=>'12'],
            ['id'=>'234','lg_code'=>'17','name'=>'Hamirpur','state_id'=>'12'],
            ['id'=>'235','lg_code'=>'18','name'=>'Kangra','state_id'=>'12'],
            ['id'=>'236','lg_code'=>'19','name'=>'Kinnaur','state_id'=>'12'],
            ['id'=>'237','lg_code'=>'20','name'=>'Kullu','state_id'=>'12'],
            ['id'=>'238','lg_code'=>'21','name'=>'Lahaul And Spiti','state_id'=>'12'],
            ['id'=>'239','lg_code'=>'22','name'=>'Mandi','state_id'=>'12'],
            ['id'=>'240','lg_code'=>'23','name'=>'Shimla','state_id'=>'12'],
            ['id'=>'241','lg_code'=>'24','name'=>'Sirmaur','state_id'=>'12'],
            ['id'=>'242','lg_code'=>'25','name'=>'Solan','state_id'=>'12'],
            ['id'=>'243','lg_code'=>'26','name'=>'Una','state_id'=>'12'],
            ['id'=>'244','lg_code'=>'1','name'=>'Anantnag','state_id'=>'13'],
            ['id'=>'245','lg_code'=>'623','name'=>'Bandipora','state_id'=>'13'],
            ['id'=>'246','lg_code'=>'3','name'=>'Baramulla','state_id'=>'13'],
            ['id'=>'247','lg_code'=>'2','name'=>'Budgam','state_id'=>'13'],
            ['id'=>'248','lg_code'=>'4','name'=>'Doda','state_id'=>'13'],
            ['id'=>'249','lg_code'=>'626','name'=>'Ganderbal','state_id'=>'13'],
            ['id'=>'250','lg_code'=>'5','name'=>'Jammu','state_id'=>'13'],
            ['id'=>'251','lg_code'=>'7','name'=>'Kathua','state_id'=>'13'],
            ['id'=>'252','lg_code'=>'620','name'=>'Kishtwar','state_id'=>'13'],
            ['id'=>'253','lg_code'=>'622','name'=>'Kulgam','state_id'=>'13'],
            ['id'=>'254','lg_code'=>'8','name'=>'Kupwara','state_id'=>'13'],
            ['id'=>'255','lg_code'=>'10','name'=>'Poonch','state_id'=>'13'],
            ['id'=>'256','lg_code'=>'11','name'=>'Pulwama','state_id'=>'13'],
            ['id'=>'257','lg_code'=>'12','name'=>'Rajouri','state_id'=>'13'],
            ['id'=>'258','lg_code'=>'621','name'=>'Ramban','state_id'=>'13'],
            ['id'=>'259','lg_code'=>'627','name'=>'Reasi','state_id'=>'13'],
            ['id'=>'260','lg_code'=>'624','name'=>'Samba','state_id'=>'13'],
            ['id'=>'261','lg_code'=>'625','name'=>'Shopian','state_id'=>'13'],
            ['id'=>'262','lg_code'=>'13','name'=>'Srinagar','state_id'=>'13'],
            ['id'=>'263','lg_code'=>'14','name'=>'Udhampur','state_id'=>'13'],
            ['id'=>'264','lg_code'=>'322','name'=>'Bokaro','state_id'=>'14'],
            ['id'=>'265','lg_code'=>'323','name'=>'Chatra','state_id'=>'14'],
            ['id'=>'266','lg_code'=>'324','name'=>'Deoghar','state_id'=>'14'],
            ['id'=>'267','lg_code'=>'325','name'=>'Dhanbad','state_id'=>'14'],
            ['id'=>'268','lg_code'=>'326','name'=>'Dumka','state_id'=>'14'],
            ['id'=>'269','lg_code'=>'327','name'=>'East Singhbum','state_id'=>'14'],
            ['id'=>'270','lg_code'=>'328','name'=>'Garhwa','state_id'=>'14'],
            ['id'=>'271','lg_code'=>'329','name'=>'Giridih','state_id'=>'14'],
            ['id'=>'272','lg_code'=>'330','name'=>'Godda','state_id'=>'14'],
            ['id'=>'273','lg_code'=>'331','name'=>'Gumla','state_id'=>'14'],
            ['id'=>'274','lg_code'=>'332','name'=>'Hazaribagh','state_id'=>'14'],
            ['id'=>'275','lg_code'=>'333','name'=>'Jamtara','state_id'=>'14'],
            ['id'=>'276','lg_code'=>'606','name'=>'Khunti','state_id'=>'14'],
            ['id'=>'277','lg_code'=>'334','name'=>'Koderma','state_id'=>'14'],
            ['id'=>'278','lg_code'=>'335','name'=>'Latehar','state_id'=>'14'],
            ['id'=>'279','lg_code'=>'336','name'=>'Lohardaga','state_id'=>'14'],
            ['id'=>'280','lg_code'=>'337','name'=>'Pakur','state_id'=>'14'],
            ['id'=>'281','lg_code'=>'338','name'=>'Palamu','state_id'=>'14'],
            ['id'=>'282','lg_code'=>'607','name'=>'Ramgarh','state_id'=>'14'],
            ['id'=>'283','lg_code'=>'339','name'=>'Ranchi','state_id'=>'14'],
            ['id'=>'284','lg_code'=>'340','name'=>'Sahebganj','state_id'=>'14'],
            ['id'=>'285','lg_code'=>'341','name'=>'Saraikela Kharsawan','state_id'=>'14'],
            ['id'=>'286','lg_code'=>'342','name'=>'Simdega','state_id'=>'14'],
            ['id'=>'287','lg_code'=>'343','name'=>'West Singhbhum','state_id'=>'14'],
            ['id'=>'288','lg_code'=>'524','name'=>'Bagalkote','state_id'=>'15'],
            ['id'=>'289','lg_code'=>'528','name'=>'Ballari','state_id'=>'15'],
            ['id'=>'290','lg_code'=>'527','name'=>'Belagavi','state_id'=>'15'],
            ['id'=>'291','lg_code'=>'526','name'=>'Bengaluru Rural','state_id'=>'15'],
            ['id'=>'292','lg_code'=>'525','name'=>'Bengaluru Urban','state_id'=>'15'],
            ['id'=>'293','lg_code'=>'529','name'=>'Bidar','state_id'=>'15'],
            ['id'=>'294','lg_code'=>'531','name'=>'Chamarajanagar','state_id'=>'15'],
            ['id'=>'295','lg_code'=>'630','name'=>'Chikkaballapura','state_id'=>'15'],
            ['id'=>'296','lg_code'=>'532','name'=>'Chikkamagaluru','state_id'=>'15'],
            ['id'=>'297','lg_code'=>'533','name'=>'Chitradurga','state_id'=>'15'],
            ['id'=>'298','lg_code'=>'534','name'=>'Dakshina Kannada','state_id'=>'15'],
            ['id'=>'299','lg_code'=>'535','name'=>'Davanagere','state_id'=>'15'],
            ['id'=>'300','lg_code'=>'536','name'=>'Dharwad','state_id'=>'15'],
            ['id'=>'301','lg_code'=>'537','name'=>'Gadag','state_id'=>'15'],
            ['id'=>'302','lg_code'=>'539','name'=>'Hassan','state_id'=>'15'],
            ['id'=>'303','lg_code'=>'540','name'=>'Haveri','state_id'=>'15'],
            ['id'=>'304','lg_code'=>'538','name'=>'Kalaburagi','state_id'=>'15'],
            ['id'=>'305','lg_code'=>'541','name'=>'Kodagu','state_id'=>'15'],
            ['id'=>'306','lg_code'=>'542','name'=>'Kolar','state_id'=>'15'],
            ['id'=>'307','lg_code'=>'543','name'=>'Koppal','state_id'=>'15'],
            ['id'=>'308','lg_code'=>'544','name'=>'Mandya','state_id'=>'15'],
            ['id'=>'309','lg_code'=>'545','name'=>'Mysuru','state_id'=>'15'],
            ['id'=>'310','lg_code'=>'546','name'=>'Raichur','state_id'=>'15'],
            ['id'=>'311','lg_code'=>'631','name'=>'Ramanagara','state_id'=>'15'],
            ['id'=>'312','lg_code'=>'547','name'=>'Shivamogga','state_id'=>'15'],
            ['id'=>'313','lg_code'=>'548','name'=>'Tumakuru','state_id'=>'15'],
            ['id'=>'314','lg_code'=>'549','name'=>'Udupi','state_id'=>'15'],
            ['id'=>'315','lg_code'=>'550','name'=>'Uttara Kannada','state_id'=>'15'],
            ['id'=>'316','lg_code'=>'738','name'=>'Vijayanagara','state_id'=>'15'],
            ['id'=>'317','lg_code'=>'530','name'=>'Vijayapura','state_id'=>'15'],
            ['id'=>'318','lg_code'=>'635','name'=>'Yadgir','state_id'=>'15'],
            ['id'=>'319','lg_code'=>'554','name'=>'Alappuzha','state_id'=>'16'],
            ['id'=>'320','lg_code'=>'555','name'=>'Ernakulam','state_id'=>'16'],
            ['id'=>'321','lg_code'=>'556','name'=>'Idukki','state_id'=>'16'],
            ['id'=>'322','lg_code'=>'557','name'=>'Kannur','state_id'=>'16'],
            ['id'=>'323','lg_code'=>'558','name'=>'Kasaragod','state_id'=>'16'],
            ['id'=>'324','lg_code'=>'559','name'=>'Kollam','state_id'=>'16'],
            ['id'=>'325','lg_code'=>'560','name'=>'Kottayam','state_id'=>'16'],
            ['id'=>'326','lg_code'=>'561','name'=>'Kozhikode','state_id'=>'16'],
            ['id'=>'327','lg_code'=>'562','name'=>'Malappuram','state_id'=>'16'],
            ['id'=>'328','lg_code'=>'563','name'=>'Palakkad','state_id'=>'16'],
            ['id'=>'329','lg_code'=>'564','name'=>'Pathanamthitta','state_id'=>'16'],
            ['id'=>'330','lg_code'=>'565','name'=>'Thiruvananthapuram','state_id'=>'16'],
            ['id'=>'331','lg_code'=>'566','name'=>'Thrissur','state_id'=>'16'],
            ['id'=>'332','lg_code'=>'567','name'=>'Wayanad','state_id'=>'16'],
            ['id'=>'333','lg_code'=>'6','name'=>'Kargil','state_id'=>'17'],
            ['id'=>'334','lg_code'=>'9','name'=>'Leh Ladakh','state_id'=>'17'],
            ['id'=>'335','lg_code'=>'553','name'=>'Lakshadweep District','state_id'=>'18'],
            ['id'=>'336','lg_code'=>'667','name'=>'Agar-Malwa','state_id'=>'19'],
            ['id'=>'337','lg_code'=>'639','name'=>'Alirajpur','state_id'=>'19'],
            ['id'=>'338','lg_code'=>'390','name'=>'Anuppur','state_id'=>'19'],
            ['id'=>'339','lg_code'=>'391','name'=>'Ashoknagar','state_id'=>'19'],
            ['id'=>'340','lg_code'=>'392','name'=>'Balaghat','state_id'=>'19'],
            ['id'=>'341','lg_code'=>'393','name'=>'Barwani','state_id'=>'19'],
            ['id'=>'342','lg_code'=>'394','name'=>'Betul','state_id'=>'19'],
            ['id'=>'343','lg_code'=>'395','name'=>'Bhind','state_id'=>'19'],
            ['id'=>'344','lg_code'=>'396','name'=>'Bhopal','state_id'=>'19'],
            ['id'=>'345','lg_code'=>'397','name'=>'Burhanpur','state_id'=>'19'],
            ['id'=>'346','lg_code'=>'398','name'=>'Chhatarpur','state_id'=>'19'],
            ['id'=>'347','lg_code'=>'399','name'=>'Chhindwara','state_id'=>'19'],
            ['id'=>'348','lg_code'=>'400','name'=>'Damoh','state_id'=>'19'],
            ['id'=>'349','lg_code'=>'401','name'=>'Datia','state_id'=>'19'],
            ['id'=>'350','lg_code'=>'402','name'=>'Dewas','state_id'=>'19'],
            ['id'=>'351','lg_code'=>'403','name'=>'Dhar','state_id'=>'19'],
            ['id'=>'352','lg_code'=>'404','name'=>'Dindori','state_id'=>'19'],
            ['id'=>'353','lg_code'=>'406','name'=>'Guna','state_id'=>'19'],
            ['id'=>'354','lg_code'=>'407','name'=>'Gwalior','state_id'=>'19'],
            ['id'=>'355','lg_code'=>'408','name'=>'Harda','state_id'=>'19'],
            ['id'=>'356','lg_code'=>'410','name'=>'Indore','state_id'=>'19'],
            ['id'=>'357','lg_code'=>'411','name'=>'Jabalpur','state_id'=>'19'],
            ['id'=>'358','lg_code'=>'412','name'=>'Jhabua','state_id'=>'19'],
            ['id'=>'359','lg_code'=>'413','name'=>'Katni','state_id'=>'19'],
            ['id'=>'360','lg_code'=>'405','name'=>'Khandwa (East Nimar)','state_id'=>'19'],
            ['id'=>'361','lg_code'=>'414','name'=>'Khargone (West Nimar)','state_id'=>'19'],
            ['id'=>'362','lg_code'=>'784','name'=>'Maihar','state_id'=>'19'],
            ['id'=>'363','lg_code'=>'415','name'=>'Mandla','state_id'=>'19'],
            ['id'=>'364','lg_code'=>'416','name'=>'Mandsaur','state_id'=>'19'],
            ['id'=>'365','lg_code'=>'766','name'=>'MAUGANJ','state_id'=>'19'],
            ['id'=>'366','lg_code'=>'417','name'=>'Morena','state_id'=>'19'],
            ['id'=>'367','lg_code'=>'409','name'=>'Narmadapuram','state_id'=>'19'],
            ['id'=>'368','lg_code'=>'418','name'=>'Narsimhapur','state_id'=>'19'],
            ['id'=>'369','lg_code'=>'419','name'=>'Neemuch','state_id'=>'19'],
            ['id'=>'370','lg_code'=>'722','name'=>'Niwari','state_id'=>'19'],
            ['id'=>'371','lg_code'=>'785','name'=>'Pandhurna','state_id'=>'19'],
            ['id'=>'372','lg_code'=>'420','name'=>'Panna','state_id'=>'19'],
            ['id'=>'373','lg_code'=>'421','name'=>'Raisen','state_id'=>'19'],
            ['id'=>'374','lg_code'=>'422','name'=>'Rajgarh','state_id'=>'19'],
            ['id'=>'375','lg_code'=>'423','name'=>'Ratlam','state_id'=>'19'],
            ['id'=>'376','lg_code'=>'424','name'=>'Rewa','state_id'=>'19'],
            ['id'=>'377','lg_code'=>'425','name'=>'Sagar','state_id'=>'19'],
            ['id'=>'378','lg_code'=>'426','name'=>'Satna','state_id'=>'19'],
            ['id'=>'379','lg_code'=>'427','name'=>'Sehore','state_id'=>'19'],
            ['id'=>'380','lg_code'=>'428','name'=>'Seoni','state_id'=>'19'],
            ['id'=>'381','lg_code'=>'429','name'=>'Shahdol','state_id'=>'19'],
            ['id'=>'382','lg_code'=>'430','name'=>'Shajapur','state_id'=>'19'],
            ['id'=>'383','lg_code'=>'431','name'=>'Sheopur','state_id'=>'19'],
            ['id'=>'384','lg_code'=>'432','name'=>'Shivpuri','state_id'=>'19'],
            ['id'=>'385','lg_code'=>'433','name'=>'Sidhi','state_id'=>'19'],
            ['id'=>'386','lg_code'=>'638','name'=>'Singrauli','state_id'=>'19'],
            ['id'=>'387','lg_code'=>'434','name'=>'Tikamgarh','state_id'=>'19'],
            ['id'=>'388','lg_code'=>'435','name'=>'Ujjain','state_id'=>'19'],
            ['id'=>'389','lg_code'=>'436','name'=>'Umaria','state_id'=>'19'],
            ['id'=>'390','lg_code'=>'437','name'=>'Vidisha','state_id'=>'19'],
            ['id'=>'391','lg_code'=>'466','name'=>'Ahilyanagar','state_id'=>'20'],
            ['id'=>'392','lg_code'=>'467','name'=>'Akola','state_id'=>'20'],
            ['id'=>'393','lg_code'=>'468','name'=>'Amravati','state_id'=>'20'],
            ['id'=>'394','lg_code'=>'470','name'=>'Beed','state_id'=>'20'],
            ['id'=>'395','lg_code'=>'471','name'=>'Bhandara','state_id'=>'20'],
            ['id'=>'396','lg_code'=>'472','name'=>'Buldhana','state_id'=>'20'],
            ['id'=>'397','lg_code'=>'473','name'=>'Chandrapur','state_id'=>'20'],
            ['id'=>'398','lg_code'=>'469','name'=>'Chhatrapati Sambhajinagar','state_id'=>'20'],
            ['id'=>'399','lg_code'=>'488','name'=>'Dharashiv','state_id'=>'20'],
            ['id'=>'400','lg_code'=>'474','name'=>'Dhule','state_id'=>'20'],
            ['id'=>'401','lg_code'=>'475','name'=>'Gadchiroli','state_id'=>'20'],
            ['id'=>'402','lg_code'=>'476','name'=>'Gondia','state_id'=>'20'],
            ['id'=>'403','lg_code'=>'477','name'=>'Hingoli','state_id'=>'20'],
            ['id'=>'404','lg_code'=>'478','name'=>'Jalgaon','state_id'=>'20'],
            ['id'=>'405','lg_code'=>'479','name'=>'Jalna','state_id'=>'20'],
            ['id'=>'406','lg_code'=>'480','name'=>'Kolhapur','state_id'=>'20'],
            ['id'=>'407','lg_code'=>'481','name'=>'Latur','state_id'=>'20'],
            ['id'=>'408','lg_code'=>'482','name'=>'Mumbai','state_id'=>'20'],
            ['id'=>'409','lg_code'=>'483','name'=>'Mumbai Suburban','state_id'=>'20'],
            ['id'=>'410','lg_code'=>'484','name'=>'Nagpur','state_id'=>'20'],
            ['id'=>'411','lg_code'=>'485','name'=>'Nanded','state_id'=>'20'],
            ['id'=>'412','lg_code'=>'486','name'=>'Nandurbar','state_id'=>'20'],
            ['id'=>'413','lg_code'=>'487','name'=>'Nashik','state_id'=>'20'],
            ['id'=>'414','lg_code'=>'665','name'=>'Palghar','state_id'=>'20'],
            ['id'=>'415','lg_code'=>'489','name'=>'Parbhani','state_id'=>'20'],
            ['id'=>'416','lg_code'=>'490','name'=>'Pune','state_id'=>'20'],
            ['id'=>'417','lg_code'=>'491','name'=>'Raigad','state_id'=>'20'],
            ['id'=>'418','lg_code'=>'492','name'=>'Ratnagiri','state_id'=>'20'],
            ['id'=>'419','lg_code'=>'493','name'=>'Sangli','state_id'=>'20'],
            ['id'=>'420','lg_code'=>'494','name'=>'Satara','state_id'=>'20'],
            ['id'=>'421','lg_code'=>'495','name'=>'Sindhudurg','state_id'=>'20'],
            ['id'=>'422','lg_code'=>'496','name'=>'Solapur','state_id'=>'20'],
            ['id'=>'423','lg_code'=>'497','name'=>'Thane','state_id'=>'20'],
            ['id'=>'424','lg_code'=>'498','name'=>'Wardha','state_id'=>'20'],
            ['id'=>'425','lg_code'=>'499','name'=>'Washim','state_id'=>'20'],
            ['id'=>'426','lg_code'=>'500','name'=>'Yavatmal','state_id'=>'20'],
            ['id'=>'427','lg_code'=>'252','name'=>'Bishnupur','state_id'=>'21'],
            ['id'=>'428','lg_code'=>'253','name'=>'Chandel','state_id'=>'21'],
            ['id'=>'429','lg_code'=>'254','name'=>'Churachandpur','state_id'=>'21'],
            ['id'=>'430','lg_code'=>'255','name'=>'Imphal East','state_id'=>'21'],
            ['id'=>'431','lg_code'=>'256','name'=>'Imphal West','state_id'=>'21'],
            ['id'=>'432','lg_code'=>'713','name'=>'Jiribam','state_id'=>'21'],
            ['id'=>'433','lg_code'=>'711','name'=>'Kakching','state_id'=>'21'],
            ['id'=>'434','lg_code'=>'717','name'=>'Kamjong','state_id'=>'21'],
            ['id'=>'435','lg_code'=>'712','name'=>'Kangpokpi','state_id'=>'21'],
            ['id'=>'436','lg_code'=>'714','name'=>'Noney','state_id'=>'21'],
            ['id'=>'437','lg_code'=>'715','name'=>'Pherzawl','state_id'=>'21'],
            ['id'=>'438','lg_code'=>'257','name'=>'Senapati','state_id'=>'21'],
            ['id'=>'439','lg_code'=>'258','name'=>'Tamenglong','state_id'=>'21'],
            ['id'=>'440','lg_code'=>'716','name'=>'Tengnoupal','state_id'=>'21'],
            ['id'=>'441','lg_code'=>'259','name'=>'Thoubal','state_id'=>'21'],
            ['id'=>'442','lg_code'=>'260','name'=>'Ukhrul','state_id'=>'21'],
            ['id'=>'443','lg_code'=>'740','name'=>'Eastern West Khasi Hills','state_id'=>'22'],
            ['id'=>'444','lg_code'=>'273','name'=>'East Garo Hills','state_id'=>'22'],
            ['id'=>'445','lg_code'=>'657','name'=>'East Jaintia Hills','state_id'=>'22'],
            ['id'=>'446','lg_code'=>'274','name'=>'East Khasi Hills','state_id'=>'22'],
            ['id'=>'447','lg_code'=>'656','name'=>'North Garo Hills','state_id'=>'22'],
            ['id'=>'448','lg_code'=>'276','name'=>'Ri Bhoi','state_id'=>'22'],
            ['id'=>'449','lg_code'=>'277','name'=>'South Garo Hills','state_id'=>'22'],
            ['id'=>'450','lg_code'=>'663','name'=>'South West Garo Hills','state_id'=>'22'],
            ['id'=>'451','lg_code'=>'658','name'=>'South West Khasi Hills','state_id'=>'22'],
            ['id'=>'452','lg_code'=>'278','name'=>'West Garo Hills','state_id'=>'22'],
            ['id'=>'453','lg_code'=>'275','name'=>'West Jaintia Hills','state_id'=>'22'],
            ['id'=>'454','lg_code'=>'279','name'=>'West Khasi Hills','state_id'=>'22'],
            ['id'=>'455','lg_code'=>'261','name'=>'Aizawl','state_id'=>'23'],
            ['id'=>'456','lg_code'=>'262','name'=>'Champhai','state_id'=>'23'],
            ['id'=>'457','lg_code'=>'726','name'=>'Hnahthial','state_id'=>'23'],
            ['id'=>'458','lg_code'=>'728','name'=>'Khawzawl','state_id'=>'23'],
            ['id'=>'459','lg_code'=>'263','name'=>'Kolasib','state_id'=>'23'],
            ['id'=>'460','lg_code'=>'264','name'=>'Lawngtlai','state_id'=>'23'],
            ['id'=>'461','lg_code'=>'265','name'=>'Lunglei','state_id'=>'23'],
            ['id'=>'462','lg_code'=>'266','name'=>'Mamit','state_id'=>'23'],
            ['id'=>'463','lg_code'=>'727','name'=>'Saitual','state_id'=>'23'],
            ['id'=>'464','lg_code'=>'268','name'=>'Serchhip','state_id'=>'23'],
            ['id'=>'465','lg_code'=>'267','name'=>'Siaha','state_id'=>'23'],
            ['id'=>'466','lg_code'=>'758','name'=>'Chumoukedima','state_id'=>'24'],
            ['id'=>'467','lg_code'=>'244','name'=>'Dimapur','state_id'=>'24'],
            ['id'=>'468','lg_code'=>'614','name'=>'Kiphire','state_id'=>'24'],
            ['id'=>'469','lg_code'=>'245','name'=>'Kohima','state_id'=>'24'],
            ['id'=>'470','lg_code'=>'615','name'=>'Longleng','state_id'=>'24'],
            ['id'=>'471','lg_code'=>'246','name'=>'Mokokchung','state_id'=>'24'],
            ['id'=>'472','lg_code'=>'247','name'=>'Mon','state_id'=>'24'],
            ['id'=>'473','lg_code'=>'764','name'=>'Niuland','state_id'=>'24'],
            ['id'=>'474','lg_code'=>'736','name'=>'Noklak','state_id'=>'24'],
            ['id'=>'475','lg_code'=>'613','name'=>'Peren','state_id'=>'24'],
            ['id'=>'476','lg_code'=>'248','name'=>'Phek','state_id'=>'24'],
            ['id'=>'477','lg_code'=>'765','name'=>'Shamator','state_id'=>'24'],
            ['id'=>'478','lg_code'=>'757','name'=>'Tseminyu','state_id'=>'24'],
            ['id'=>'479','lg_code'=>'249','name'=>'Tuensang','state_id'=>'24'],
            ['id'=>'480','lg_code'=>'250','name'=>'Wokha','state_id'=>'24'],
            ['id'=>'481','lg_code'=>'251','name'=>'Zunheboto','state_id'=>'24'],
            ['id'=>'482','lg_code'=>'344','name'=>'Anugul','state_id'=>'25'],
            ['id'=>'483','lg_code'=>'345','name'=>'Balangir','state_id'=>'25'],
            ['id'=>'484','lg_code'=>'346','name'=>'Baleshwar','state_id'=>'25'],
            ['id'=>'485','lg_code'=>'347','name'=>'Bargarh','state_id'=>'25'],
            ['id'=>'486','lg_code'=>'348','name'=>'Bhadrak','state_id'=>'25'],
            ['id'=>'487','lg_code'=>'349','name'=>'Boudh','state_id'=>'25'],
            ['id'=>'488','lg_code'=>'350','name'=>'Cuttack','state_id'=>'25'],
            ['id'=>'489','lg_code'=>'351','name'=>'Deogarh','state_id'=>'25'],
            ['id'=>'490','lg_code'=>'352','name'=>'Dhenkanal','state_id'=>'25'],
            ['id'=>'491','lg_code'=>'353','name'=>'Gajapati','state_id'=>'25'],
            ['id'=>'492','lg_code'=>'354','name'=>'Ganjam','state_id'=>'25'],
            ['id'=>'493','lg_code'=>'355','name'=>'Jagatsinghapur','state_id'=>'25'],
            ['id'=>'494','lg_code'=>'356','name'=>'Jajapur','state_id'=>'25'],
            ['id'=>'495','lg_code'=>'357','name'=>'Jharsuguda','state_id'=>'25'],
            ['id'=>'496','lg_code'=>'358','name'=>'Kalahandi','state_id'=>'25'],
            ['id'=>'497','lg_code'=>'359','name'=>'Kandhamal','state_id'=>'25'],
            ['id'=>'498','lg_code'=>'360','name'=>'Kendrapara','state_id'=>'25'],
            ['id'=>'499','lg_code'=>'361','name'=>'Kendujhar','state_id'=>'25'],
            ['id'=>'500','lg_code'=>'362','name'=>'Khordha','state_id'=>'25'],
            ['id'=>'501','lg_code'=>'363','name'=>'Koraput','state_id'=>'25'],
            ['id'=>'502','lg_code'=>'364','name'=>'Malkangiri','state_id'=>'25'],
            ['id'=>'503','lg_code'=>'365','name'=>'Mayurbhanj','state_id'=>'25'],
            ['id'=>'504','lg_code'=>'366','name'=>'Nabarangpur','state_id'=>'25'],
            ['id'=>'505','lg_code'=>'367','name'=>'Nayagarh','state_id'=>'25'],
            ['id'=>'506','lg_code'=>'368','name'=>'Nuapada','state_id'=>'25'],
            ['id'=>'507','lg_code'=>'369','name'=>'Puri','state_id'=>'25'],
            ['id'=>'508','lg_code'=>'370','name'=>'Rayagada','state_id'=>'25'],
            ['id'=>'509','lg_code'=>'371','name'=>'Sambalpur','state_id'=>'25'],
            ['id'=>'510','lg_code'=>'372','name'=>'Sonepur','state_id'=>'25'],
            ['id'=>'511','lg_code'=>'373','name'=>'Sundargarh','state_id'=>'25'],
            ['id'=>'512','lg_code'=>'598','name'=>'Karaikal','state_id'=>'26'],
            ['id'=>'513','lg_code'=>'600','name'=>'Puducherry','state_id'=>'26'],
            ['id'=>'514','lg_code'=>'27','name'=>'Amritsar','state_id'=>'27'],
            ['id'=>'515','lg_code'=>'605','name'=>'Barnala','state_id'=>'27'],
            ['id'=>'516','lg_code'=>'28','name'=>'Bathinda','state_id'=>'27'],
            ['id'=>'517','lg_code'=>'29','name'=>'Faridkot','state_id'=>'27'],
            ['id'=>'518','lg_code'=>'30','name'=>'Fatehgarh Sahib','state_id'=>'27'],
            ['id'=>'519','lg_code'=>'651','name'=>'Fazilka','state_id'=>'27'],
            ['id'=>'520','lg_code'=>'31','name'=>'Ferozepur','state_id'=>'27'],
            ['id'=>'521','lg_code'=>'32','name'=>'Gurdaspur','state_id'=>'27'],
            ['id'=>'522','lg_code'=>'33','name'=>'Hoshiarpur','state_id'=>'27'],
            ['id'=>'523','lg_code'=>'34','name'=>'Jalandhar','state_id'=>'27'],
            ['id'=>'524','lg_code'=>'35','name'=>'Kapurthala','state_id'=>'27'],
            ['id'=>'525','lg_code'=>'36','name'=>'Ludhiana','state_id'=>'27'],
            ['id'=>'526','lg_code'=>'737','name'=>'Malerkotla','state_id'=>'27'],
            ['id'=>'527','lg_code'=>'37','name'=>'Mansa','state_id'=>'27'],
            ['id'=>'528','lg_code'=>'38','name'=>'Moga','state_id'=>'27'],
            ['id'=>'529','lg_code'=>'662','name'=>'Pathankot','state_id'=>'27'],
            ['id'=>'530','lg_code'=>'41','name'=>'Patiala','state_id'=>'27'],
            ['id'=>'531','lg_code'=>'42','name'=>'Rupnagar','state_id'=>'27'],
            ['id'=>'532','lg_code'=>'43','name'=>'Sangrur','state_id'=>'27'],
            ['id'=>'533','lg_code'=>'608','name'=>'S.A.S Nagar','state_id'=>'27'],
            ['id'=>'534','lg_code'=>'40','name'=>'Shahid Bhagat Singh Nagar','state_id'=>'27'],
            ['id'=>'535','lg_code'=>'39','name'=>'Sri Muktsar Sahib','state_id'=>'27'],
            ['id'=>'536','lg_code'=>'609','name'=>'Tarn Taran','state_id'=>'27'],
            ['id'=>'537','lg_code'=>'86','name'=>'Ajmer','state_id'=>'28'],
            ['id'=>'538','lg_code'=>'87','name'=>'Alwar','state_id'=>'28'],
            ['id'=>'539','lg_code'=>'775','name'=>'Balotra','state_id'=>'28'],
            ['id'=>'540','lg_code'=>'88','name'=>'Banswara','state_id'=>'28'],
            ['id'=>'541','lg_code'=>'89','name'=>'Baran','state_id'=>'28'],
            ['id'=>'542','lg_code'=>'90','name'=>'Barmer','state_id'=>'28'],
            ['id'=>'543','lg_code'=>'774','name'=>'Beawar','state_id'=>'28'],
            ['id'=>'544','lg_code'=>'91','name'=>'Bharatpur','state_id'=>'28'],
            ['id'=>'545','lg_code'=>'92','name'=>'Bhilwara','state_id'=>'28'],
            ['id'=>'546','lg_code'=>'93','name'=>'Bikaner','state_id'=>'28'],
            ['id'=>'547','lg_code'=>'94','name'=>'Bundi','state_id'=>'28'],
            ['id'=>'548','lg_code'=>'95','name'=>'Chittorgarh','state_id'=>'28'],
            ['id'=>'549','lg_code'=>'96','name'=>'Churu','state_id'=>'28'],
            ['id'=>'550','lg_code'=>'97','name'=>'Dausa','state_id'=>'28'],
            ['id'=>'551','lg_code'=>'767','name'=>'Deeg','state_id'=>'28'],
            ['id'=>'552','lg_code'=>'98','name'=>'Dholpur','state_id'=>'28'],
            ['id'=>'553','lg_code'=>'768','name'=>'Didwana-Kuchaman','state_id'=>'28'],
            ['id'=>'554','lg_code'=>'99','name'=>'Dungarpur','state_id'=>'28'],
            ['id'=>'555','lg_code'=>'100','name'=>'Ganganagar','state_id'=>'28'],
            ['id'=>'556','lg_code'=>'101','name'=>'Hanumangarh','state_id'=>'28'],
            ['id'=>'557','lg_code'=>'102','name'=>'Jaipur','state_id'=>'28'],
            ['id'=>'558','lg_code'=>'103','name'=>'Jaisalmer','state_id'=>'28'],
            ['id'=>'559','lg_code'=>'104','name'=>'Jalore','state_id'=>'28'],
            ['id'=>'560','lg_code'=>'105','name'=>'Jhalawar','state_id'=>'28'],
            ['id'=>'561','lg_code'=>'106','name'=>'Jhunjhunu','state_id'=>'28'],
            ['id'=>'562','lg_code'=>'107','name'=>'Jodhpur','state_id'=>'28'],
            ['id'=>'563','lg_code'=>'108','name'=>'Karauli','state_id'=>'28'],
            ['id'=>'564','lg_code'=>'770','name'=>'Khairthal-Tijara','state_id'=>'28'],
            ['id'=>'565','lg_code'=>'109','name'=>'Kota','state_id'=>'28'],
            ['id'=>'566','lg_code'=>'782','name'=>'Kotputli-Behror','state_id'=>'28'],
            ['id'=>'567','lg_code'=>'110','name'=>'Nagaur','state_id'=>'28'],
            ['id'=>'568','lg_code'=>'111','name'=>'Pali','state_id'=>'28'],
            ['id'=>'569','lg_code'=>'772','name'=>'Phalodi','state_id'=>'28'],
            ['id'=>'570','lg_code'=>'629','name'=>'Pratapgarh','state_id'=>'28'],
            ['id'=>'571','lg_code'=>'112','name'=>'Rajsamand','state_id'=>'28'],
            ['id'=>'572','lg_code'=>'777','name'=>'Salumbar','state_id'=>'28'],
            ['id'=>'573','lg_code'=>'113','name'=>'Sawai Madhopur','state_id'=>'28'],
            ['id'=>'574','lg_code'=>'114','name'=>'Sikar','state_id'=>'28'],
            ['id'=>'575','lg_code'=>'115','name'=>'Sirohi','state_id'=>'28'],
            ['id'=>'576','lg_code'=>'116','name'=>'Tonk','state_id'=>'28'],
            ['id'=>'577','lg_code'=>'117','name'=>'Udaipur','state_id'=>'28'],
            ['id'=>'578','lg_code'=>'225','name'=>'Gangtok','state_id'=>'29'],
            ['id'=>'579','lg_code'=>'228','name'=>'Gyalshing','state_id'=>'29'],
            ['id'=>'580','lg_code'=>'226','name'=>'Mangan','state_id'=>'29'],
            ['id'=>'581','lg_code'=>'227','name'=>'Namchi','state_id'=>'29'],
            ['id'=>'582','lg_code'=>'741','name'=>'Pakyong','state_id'=>'29'],
            ['id'=>'583','lg_code'=>'742','name'=>'Soreng','state_id'=>'29'],
            ['id'=>'584','lg_code'=>'610','name'=>'Ariyalur','state_id'=>'30'],
            ['id'=>'585','lg_code'=>'730','name'=>'Chengalpattu','state_id'=>'30'],
            ['id'=>'586','lg_code'=>'568','name'=>'Chennai','state_id'=>'30'],
            ['id'=>'587','lg_code'=>'569','name'=>'Coimbatore','state_id'=>'30'],
            ['id'=>'588','lg_code'=>'570','name'=>'Cuddalore','state_id'=>'30'],
            ['id'=>'589','lg_code'=>'571','name'=>'Dharmapuri','state_id'=>'30'],
            ['id'=>'590','lg_code'=>'572','name'=>'Dindigul','state_id'=>'30'],
            ['id'=>'591','lg_code'=>'573','name'=>'Erode','state_id'=>'30'],
            ['id'=>'592','lg_code'=>'729','name'=>'Kallakurichi','state_id'=>'30'],
            ['id'=>'593','lg_code'=>'574','name'=>'Kancheepuram','state_id'=>'30'],
            ['id'=>'594','lg_code'=>'575','name'=>'Kanniyakumari','state_id'=>'30'],
            ['id'=>'595','lg_code'=>'576','name'=>'Karur','state_id'=>'30'],
            ['id'=>'596','lg_code'=>'577','name'=>'Krishnagiri','state_id'=>'30'],
            ['id'=>'597','lg_code'=>'578','name'=>'Madurai','state_id'=>'30'],
            ['id'=>'598','lg_code'=>'735','name'=>'Mayiladuthurai','state_id'=>'30'],
            ['id'=>'599','lg_code'=>'579','name'=>'Nagapattinam','state_id'=>'30'],
            ['id'=>'600','lg_code'=>'580','name'=>'Namakkal','state_id'=>'30'],
            ['id'=>'601','lg_code'=>'581','name'=>'Perambalur','state_id'=>'30'],
            ['id'=>'602','lg_code'=>'582','name'=>'Pudukkottai','state_id'=>'30'],
            ['id'=>'603','lg_code'=>'583','name'=>'Ramanathapuram','state_id'=>'30'],
            ['id'=>'604','lg_code'=>'731','name'=>'Ranipet','state_id'=>'30'],
            ['id'=>'605','lg_code'=>'584','name'=>'Salem','state_id'=>'30'],
            ['id'=>'606','lg_code'=>'585','name'=>'Sivaganga','state_id'=>'30'],
            ['id'=>'607','lg_code'=>'733','name'=>'Tenkasi','state_id'=>'30'],
            ['id'=>'608','lg_code'=>'586','name'=>'Thanjavur','state_id'=>'30'],
            ['id'=>'609','lg_code'=>'588','name'=>'Theni','state_id'=>'30'],
            ['id'=>'610','lg_code'=>'587','name'=>'The Nilgiris','state_id'=>'30'],
            ['id'=>'611','lg_code'=>'589','name'=>'Thiruvallur','state_id'=>'30'],
            ['id'=>'612','lg_code'=>'590','name'=>'Thiruvarur','state_id'=>'30'],
            ['id'=>'613','lg_code'=>'594','name'=>'Thoothukkudi','state_id'=>'30'],
            ['id'=>'614','lg_code'=>'591','name'=>'Tiruchirappalli','state_id'=>'30'],
            ['id'=>'615','lg_code'=>'592','name'=>'Tirunelveli','state_id'=>'30'],
            ['id'=>'616','lg_code'=>'732','name'=>'Tirupathur','state_id'=>'30'],
            ['id'=>'617','lg_code'=>'634','name'=>'Tiruppur','state_id'=>'30'],
            ['id'=>'618','lg_code'=>'593','name'=>'Tiruvannamalai','state_id'=>'30'],
            ['id'=>'619','lg_code'=>'595','name'=>'Vellore','state_id'=>'30'],
            ['id'=>'620','lg_code'=>'596','name'=>'Viluppuram','state_id'=>'30'],
            ['id'=>'621','lg_code'=>'597','name'=>'Virudhunagar','state_id'=>'30'],
            ['id'=>'622','lg_code'=>'501','name'=>'Adilabad','state_id'=>'31'],
            ['id'=>'623','lg_code'=>'690','name'=>'Bhadradri Kothagudem','state_id'=>'31'],
            ['id'=>'624','lg_code'=>'686','name'=>'Hanumakonda','state_id'=>'31'],
            ['id'=>'625','lg_code'=>'507','name'=>'Hyderabad','state_id'=>'31'],
            ['id'=>'626','lg_code'=>'681','name'=>'Jagitial','state_id'=>'31'],
            ['id'=>'627','lg_code'=>'689','name'=>'Jangoan','state_id'=>'31'],
            ['id'=>'628','lg_code'=>'687','name'=>'Jayashankar Bhupalapally','state_id'=>'31'],
            ['id'=>'629','lg_code'=>'695','name'=>'Jogulamba Gadwal','state_id'=>'31'],
            ['id'=>'630','lg_code'=>'685','name'=>'Kamareddy','state_id'=>'31'],
            ['id'=>'631','lg_code'=>'508','name'=>'Karimnagar','state_id'=>'31'],
            ['id'=>'632','lg_code'=>'509','name'=>'Khammam','state_id'=>'31'],
            ['id'=>'633','lg_code'=>'699','name'=>'Kumuram Bheem Asifabad','state_id'=>'31'],
            ['id'=>'634','lg_code'=>'688','name'=>'Mahabubabad','state_id'=>'31'],
            ['id'=>'635','lg_code'=>'512','name'=>'Mahabubnagar','state_id'=>'31'],
            ['id'=>'636','lg_code'=>'684','name'=>'Mancherial','state_id'=>'31'],
            ['id'=>'637','lg_code'=>'513','name'=>'Medak','state_id'=>'31'],
            ['id'=>'638','lg_code'=>'700','name'=>'Medchal Malkajgiri','state_id'=>'31'],
            ['id'=>'639','lg_code'=>'720','name'=>'Mulugu','state_id'=>'31'],
            ['id'=>'640','lg_code'=>'694','name'=>'Nagarkurnool','state_id'=>'31'],
            ['id'=>'641','lg_code'=>'514','name'=>'Nalgonda','state_id'=>'31'],
            ['id'=>'642','lg_code'=>'721','name'=>'Narayanpet','state_id'=>'31'],
            ['id'=>'643','lg_code'=>'680','name'=>'Nirmal','state_id'=>'31'],
            ['id'=>'644','lg_code'=>'516','name'=>'Nizamabad','state_id'=>'31'],
            ['id'=>'645','lg_code'=>'682','name'=>'Peddapalli','state_id'=>'31'],
            ['id'=>'646','lg_code'=>'683','name'=>'Rajanna Sircilla','state_id'=>'31'],
            ['id'=>'647','lg_code'=>'518','name'=>'Ranga Reddy','state_id'=>'31'],
            ['id'=>'648','lg_code'=>'691','name'=>'Sangareddy','state_id'=>'31'],
            ['id'=>'649','lg_code'=>'692','name'=>'Siddipet','state_id'=>'31'],
            ['id'=>'650','lg_code'=>'696','name'=>'Suryapet','state_id'=>'31'],
            ['id'=>'651','lg_code'=>'698','name'=>'Vikarabad','state_id'=>'31'],
            ['id'=>'652','lg_code'=>'693','name'=>'Wanaparthy','state_id'=>'31'],
            ['id'=>'653','lg_code'=>'522','name'=>'Warangal','state_id'=>'31'],
            ['id'=>'654','lg_code'=>'697','name'=>'Yadadri Bhuvanagiri','state_id'=>'31'],
            ['id'=>'655','lg_code'=>'465','name'=>'Dadra And Nagar Haveli','state_id'=>'32'],
            ['id'=>'656','lg_code'=>'463','name'=>'Daman','state_id'=>'32'],
            ['id'=>'657','lg_code'=>'464','name'=>'Diu','state_id'=>'32'],
            ['id'=>'658','lg_code'=>'269','name'=>'Dhalai','state_id'=>'33'],
            ['id'=>'659','lg_code'=>'654','name'=>'Gomati','state_id'=>'33'],
            ['id'=>'660','lg_code'=>'652','name'=>'Khowai','state_id'=>'33'],
            ['id'=>'661','lg_code'=>'270','name'=>'North Tripura','state_id'=>'33'],
            ['id'=>'662','lg_code'=>'653','name'=>'Sepahijala','state_id'=>'33'],
            ['id'=>'663','lg_code'=>'271','name'=>'South Tripura','state_id'=>'33'],
            ['id'=>'664','lg_code'=>'655','name'=>'Unakoti','state_id'=>'33'],
            ['id'=>'665','lg_code'=>'272','name'=>'West Tripura','state_id'=>'33'],
            ['id'=>'666','lg_code'=>'45','name'=>'Almora','state_id'=>'34'],
            ['id'=>'667','lg_code'=>'46','name'=>'Bageshwar','state_id'=>'34'],
            ['id'=>'668','lg_code'=>'47','name'=>'Chamoli','state_id'=>'34'],
            ['id'=>'669','lg_code'=>'48','name'=>'Champawat','state_id'=>'34'],
            ['id'=>'670','lg_code'=>'49','name'=>'Dehradun','state_id'=>'34'],
            ['id'=>'671','lg_code'=>'50','name'=>'Haridwar','state_id'=>'34'],
            ['id'=>'672','lg_code'=>'51','name'=>'Nainital','state_id'=>'34'],
            ['id'=>'673','lg_code'=>'52','name'=>'Pauri Garhwal','state_id'=>'34'],
            ['id'=>'674','lg_code'=>'53','name'=>'Pithoragarh','state_id'=>'34'],
            ['id'=>'675','lg_code'=>'54','name'=>'Rudra Prayag','state_id'=>'34'],
            ['id'=>'676','lg_code'=>'55','name'=>'Tehri Garhwal','state_id'=>'34'],
            ['id'=>'677','lg_code'=>'56','name'=>'Udam Singh Nagar','state_id'=>'34'],
            ['id'=>'678','lg_code'=>'57','name'=>'Uttar Kashi','state_id'=>'34'],
            ['id'=>'679','lg_code'=>'118','name'=>'Agra','state_id'=>'35'],
            ['id'=>'680','lg_code'=>'119','name'=>'Aligarh','state_id'=>'35'],
            ['id'=>'681','lg_code'=>'121','name'=>'Ambedkar Nagar','state_id'=>'35'],
            ['id'=>'682','lg_code'=>'640','name'=>'Amethi','state_id'=>'35'],
            ['id'=>'683','lg_code'=>'154','name'=>'Amroha','state_id'=>'35'],
            ['id'=>'684','lg_code'=>'122','name'=>'Auraiya','state_id'=>'35'],
            ['id'=>'685','lg_code'=>'140','name'=>'Ayodhya','state_id'=>'35'],
            ['id'=>'686','lg_code'=>'123','name'=>'Azamgarh','state_id'=>'35'],
            ['id'=>'687','lg_code'=>'124','name'=>'Baghpat','state_id'=>'35'],
            ['id'=>'688','lg_code'=>'125','name'=>'Bahraich','state_id'=>'35'],
            ['id'=>'689','lg_code'=>'126','name'=>'Ballia','state_id'=>'35'],
            ['id'=>'690','lg_code'=>'127','name'=>'Balrampur','state_id'=>'35'],
            ['id'=>'691','lg_code'=>'128','name'=>'Banda','state_id'=>'35'],
            ['id'=>'692','lg_code'=>'129','name'=>'Bara Banki','state_id'=>'35'],
            ['id'=>'693','lg_code'=>'130','name'=>'Bareilly','state_id'=>'35'],
            ['id'=>'694','lg_code'=>'131','name'=>'Basti','state_id'=>'35'],
            ['id'=>'695','lg_code'=>'179','name'=>'Bhadohi','state_id'=>'35'],
            ['id'=>'696','lg_code'=>'132','name'=>'Bijnor','state_id'=>'35'],
            ['id'=>'697','lg_code'=>'133','name'=>'Budaun','state_id'=>'35'],
            ['id'=>'698','lg_code'=>'134','name'=>'Bulandshahr','state_id'=>'35'],
            ['id'=>'699','lg_code'=>'135','name'=>'Chandauli','state_id'=>'35'],
            ['id'=>'700','lg_code'=>'136','name'=>'Chitrakoot','state_id'=>'35'],
            ['id'=>'701','lg_code'=>'137','name'=>'Deoria','state_id'=>'35'],
            ['id'=>'702','lg_code'=>'138','name'=>'Etah','state_id'=>'35'],
            ['id'=>'703','lg_code'=>'139','name'=>'Etawah','state_id'=>'35'],
            ['id'=>'704','lg_code'=>'141','name'=>'Farrukhabad','state_id'=>'35'],
            ['id'=>'705','lg_code'=>'142','name'=>'Fatehpur','state_id'=>'35'],
            ['id'=>'706','lg_code'=>'143','name'=>'Firozabad','state_id'=>'35'],
            ['id'=>'707','lg_code'=>'144','name'=>'Gautam Buddha Nagar','state_id'=>'35'],
            ['id'=>'708','lg_code'=>'145','name'=>'Ghaziabad','state_id'=>'35'],
            ['id'=>'709','lg_code'=>'146','name'=>'Ghazipur','state_id'=>'35'],
            ['id'=>'710','lg_code'=>'147','name'=>'Gonda','state_id'=>'35'],
            ['id'=>'711','lg_code'=>'148','name'=>'Gorakhpur','state_id'=>'35'],
            ['id'=>'712','lg_code'=>'149','name'=>'Hamirpur','state_id'=>'35'],
            ['id'=>'713','lg_code'=>'661','name'=>'Hapur','state_id'=>'35'],
            ['id'=>'714','lg_code'=>'150','name'=>'Hardoi','state_id'=>'35'],
            ['id'=>'715','lg_code'=>'163','name'=>'Hathras','state_id'=>'35'],
            ['id'=>'716','lg_code'=>'151','name'=>'Jalaun','state_id'=>'35'],
            ['id'=>'717','lg_code'=>'152','name'=>'Jaunpur','state_id'=>'35'],
            ['id'=>'718','lg_code'=>'153','name'=>'Jhansi','state_id'=>'35'],
            ['id'=>'719','lg_code'=>'155','name'=>'Kannauj','state_id'=>'35'],
            ['id'=>'720','lg_code'=>'156','name'=>'Kanpur Dehat','state_id'=>'35'],
            ['id'=>'721','lg_code'=>'157','name'=>'Kanpur Nagar','state_id'=>'35'],
            ['id'=>'722','lg_code'=>'633','name'=>'Kasganj','state_id'=>'35'],
            ['id'=>'723','lg_code'=>'158','name'=>'Kaushambi','state_id'=>'35'],
            ['id'=>'724','lg_code'=>'159','name'=>'Kheri','state_id'=>'35'],
            ['id'=>'725','lg_code'=>'160','name'=>'Kushinagar','state_id'=>'35'],
            ['id'=>'726','lg_code'=>'161','name'=>'Lalitpur','state_id'=>'35'],
            ['id'=>'727','lg_code'=>'162','name'=>'Lucknow','state_id'=>'35'],
            ['id'=>'728','lg_code'=>'165','name'=>'Mahoba','state_id'=>'35'],
            ['id'=>'729','lg_code'=>'164','name'=>'Mahrajganj','state_id'=>'35'],
            ['id'=>'730','lg_code'=>'166','name'=>'Mainpuri','state_id'=>'35'],
            ['id'=>'731','lg_code'=>'167','name'=>'Mathura','state_id'=>'35'],
            ['id'=>'732','lg_code'=>'168','name'=>'Mau','state_id'=>'35'],
            ['id'=>'733','lg_code'=>'169','name'=>'Meerut','state_id'=>'35'],
            ['id'=>'734','lg_code'=>'170','name'=>'Mirzapur','state_id'=>'35'],
            ['id'=>'735','lg_code'=>'171','name'=>'Moradabad','state_id'=>'35'],
            ['id'=>'736','lg_code'=>'172','name'=>'Muzaffarnagar','state_id'=>'35'],
            ['id'=>'737','lg_code'=>'173','name'=>'Pilibhit','state_id'=>'35'],
            ['id'=>'738','lg_code'=>'174','name'=>'Pratapgarh','state_id'=>'35'],
            ['id'=>'739','lg_code'=>'120','name'=>'Prayagraj','state_id'=>'35'],
            ['id'=>'740','lg_code'=>'175','name'=>'Rae Bareli','state_id'=>'35'],
            ['id'=>'741','lg_code'=>'176','name'=>'Rampur','state_id'=>'35'],
            ['id'=>'742','lg_code'=>'177','name'=>'Saharanpur','state_id'=>'35'],
            ['id'=>'743','lg_code'=>'659','name'=>'Sambhal','state_id'=>'35'],
            ['id'=>'744','lg_code'=>'178','name'=>'Sant Kabir Nagar','state_id'=>'35'],
            ['id'=>'745','lg_code'=>'180','name'=>'Shahjahanpur','state_id'=>'35'],
            ['id'=>'746','lg_code'=>'660','name'=>'Shamli','state_id'=>'35'],
            ['id'=>'747','lg_code'=>'181','name'=>'Shrawasti','state_id'=>'35'],
            ['id'=>'748','lg_code'=>'182','name'=>'Siddharthnagar','state_id'=>'35'],
            ['id'=>'749','lg_code'=>'183','name'=>'Sitapur','state_id'=>'35'],
            ['id'=>'750','lg_code'=>'184','name'=>'Sonbhadra','state_id'=>'35'],
            ['id'=>'751','lg_code'=>'185','name'=>'Sultanpur','state_id'=>'35'],
            ['id'=>'752','lg_code'=>'186','name'=>'Unnao','state_id'=>'35'],
            ['id'=>'753','lg_code'=>'187','name'=>'Varanasi','state_id'=>'35'],
            ['id'=>'754','lg_code'=>'664','name'=>'Alipurduar','state_id'=>'36'],
            ['id'=>'755','lg_code'=>'305','name'=>'Bankura','state_id'=>'36'],
            ['id'=>'756','lg_code'=>'307','name'=>'Birbhum','state_id'=>'36'],
            ['id'=>'757','lg_code'=>'308','name'=>'Cooch Behar','state_id'=>'36'],
            ['id'=>'758','lg_code'=>'310','name'=>'Dakshin Dinajpur','state_id'=>'36'],
            ['id'=>'759','lg_code'=>'309','name'=>'Darjeeling','state_id'=>'36'],
            ['id'=>'760','lg_code'=>'312','name'=>'Hooghly','state_id'=>'36'],
            ['id'=>'761','lg_code'=>'313','name'=>'Howrah','state_id'=>'36'],
            ['id'=>'762','lg_code'=>'314','name'=>'Jalpaiguri','state_id'=>'36'],
            ['id'=>'763','lg_code'=>'703','name'=>'Jhargram','state_id'=>'36'],
            ['id'=>'764','lg_code'=>'702','name'=>'Kalimpong','state_id'=>'36'],
            ['id'=>'765','lg_code'=>'315','name'=>'Kolkata','state_id'=>'36'],
            ['id'=>'766','lg_code'=>'316','name'=>'Malda','state_id'=>'36'],
            ['id'=>'767','lg_code'=>'319','name'=>'Murshidabad','state_id'=>'36'],
            ['id'=>'768','lg_code'=>'320','name'=>'Nadia','state_id'=>'36'],
            ['id'=>'769','lg_code'=>'303','name'=>'North 24 Parganas','state_id'=>'36'],
            ['id'=>'770','lg_code'=>'704','name'=>'Paschim Bardhaman','state_id'=>'36'],
            ['id'=>'771','lg_code'=>'318','name'=>'Paschim Medinipur','state_id'=>'36'],
            ['id'=>'772','lg_code'=>'306','name'=>'Purba Bardhaman','state_id'=>'36'],
            ['id'=>'773','lg_code'=>'317','name'=>'Purba Medinipur','state_id'=>'36'],
            ['id'=>'774','lg_code'=>'321','name'=>'Purulia','state_id'=>'36'],
            ['id'=>'775','lg_code'=>'304','name'=>'South 24 Parganas','state_id'=>'36'],
            ['id'=>'776','lg_code'=>'311','name'=>'Uttar Dinajpur','state_id'=>'36']
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('districts');
    }
};
